
SELECT * FROM CITY WHERE COUNTRYCODE ='USA'  AND POPULATION > 100000;


SELECT ROUND(SUM(LAT_N),4) FROM STATION WHERE (LAT_N > 38.7880) AND (LAT_N < 137.2345);


SELECT * FROM CITY;


SELECT * FROM CITY WHERE ID = 1661;


SELECT * FROM CITY ci WHERE ci.COUNTRYCODE = 'JPN';


SELECT ci.NAME FROM CITY ci WHERE ci.COUNTRYCODE = 'JPN';


SELECT s.CITY, s.STATE FROM STATION s;


SELECT DISTINCT(CITY) FROM STATION WHERE MOD(ID,2) = 0;


SELECT COUNT(s.CITY) - COUNT(DISTINCT(s.CITY)) FROM STATION s;


SELECT s.CITY,LENGTH(s.CITY) FROM STATION AS s ORDER BY LENGTH(s.CITY) ASC,s.CITY LIMIT 1;
SELECT s.CITY,LENGTH(s.CITY) FROM STATION AS s ORDER BY LENGTH(s.CITY) DESC, s.CITY LIMIT 1;


